/*
package Exception_Handling;

public class NestdeTryCatch {
    public static void main(String[] args) {
        try {
            System.out.println("outer try block running..");
            try {
                int num = Integer.parseInt("abc");
                System.out.println("Number: " + num);

            }


        }
    }
}
*/
